"""empty message

Revision ID: 9ee9dd8d2bf
Revises: None
Create Date: 2013-11-29 19:42:12.304900

"""

# revision identifiers, used by Alembic.
revision = '9ee9dd8d2bf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('first_send_interval_start', sa.Time(), nullable=True),
    sa.Column('first_send_interval_end', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content')
    )
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_key_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('sending_interval', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=2200), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_pub_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['access_key_id'], ['access_key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=2000), nullable=False),
    sa.Column('link', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=1000), nullable=True),
    sa.Column('comments', sa.String(length=2000), nullable=True),
    sa.Column('guid', sa.String(length=2000), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('enclosure_length', sa.Integer(), nullable=True),
    sa.Column('enclosure_type', sa.String(length=500), nullable=True),
    sa.Column('enclosure_url', sa.String(length=2000), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_content', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_item')
    op.drop_table('feed')
    op.drop_table('access_key')
    ### end Alembic commands ###
